/// Marks a property whose default value should be generated by `@Default`.
@attached(peer, names: prefixed(__DefaultValue_))
public macro Default(_ defaultValue: Int) = #externalMacro(module: "DefaultMacros", type: "DefaultMarkerMacro")

/// Marks a property whose default value should be generated by `@Default`.
@attached(peer, names: prefixed(__DefaultValue_))
public macro Default(_ defaultValue: Bool) = #externalMacro(module: "DefaultMacros", type: "DefaultMarkerMacro")

/// Marks a property whose default value should be generated by `@Default`.
@attached(peer, names: prefixed(__DefaultValue_))
public macro Default(_ defaultValue: String) = #externalMacro(module: "DefaultMacros", type: "DefaultMarkerMacro")

/// Marks a property whose default value should be generated by `@Default`.
@attached(peer, names: prefixed(__DefaultValue_))
public macro Default(_ defaultValue: Double) = #externalMacro(module: "DefaultMacros", type: "DefaultMarkerMacro")

/// Marks a property whose default value should be generated by `@Default`.
@attached(peer, names: prefixed(__DefaultValue_))
public macro Default(_ defaultValue: Float) = #externalMacro(module: "DefaultMacros", type: "DefaultMarkerMacro")
